running test
Failure: ImportError (The ESMFMKFILE cannot be found!) ... ERROR

======================================================================
ERROR: Failure: ImportError (The ESMFMKFILE cannot be found!)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/scratch/mpotts/gfortran_7.4.0_openmpi_O/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 12, in <module>
    from ESMF.interface.esmfmkfile import ESMFMKFILE as esmfmk
ModuleNotFoundError: No module named 'ESMF.interface.esmfmkfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/mpotts/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/glade/u/home/mpotts/.local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/glade/u/home/mpotts/.local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/glade/u/home/mpotts/.local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/glade/scratch/mpotts/gfortran_7.4.0_openmpi_O/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/glade/scratch/mpotts/gfortran_7.4.0_openmpi_O/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/glade/scratch/mpotts/gfortran_7.4.0_openmpi_O/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/glade/scratch/mpotts/gfortran_7.4.0_openmpi_O/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 14, in <module>
    raise ImportError('The ESMFMKFILE cannot be found!')
ImportError: The ESMFMKFILE cannot be found!

----------------------------------------------------------------------
XML: /glade/scratch/mpotts/gfortran_7.4.0_openmpi_O/src/addon/ESMPy/nosetests.xml
----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    subprocess.check_call(cmd)
  File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nosetests', '-vs', '--with-xunit', '-a', '!slow,!parallel', 'src/ESMF']' returned non-zero exit status 1.
